variant: fcos
version: 1.3.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - %%SSH_PUBKEY%%

systemd:
  units:
    - name: cgroups-v2-karg.service
      enabled: true
      contents: |
        [Unit]
        Description=Switch To cgroups v2
        # We run after `systemd-machine-id-commit.service` to ensure that
        # `ConditionFirstBoot=true` services won't rerun on the next boot.
        After=systemd-machine-id-commit.service
        ConditionKernelCommandLine=systemd.unified_cgroup_hierarchy
        ConditionPathExists=!/var/lib/cgroups-v2-karg.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/rpm-ostree kargs --delete=systemd.unified_cgroup_hierarchy
        ExecStart=/bin/touch /var/lib/cgroups-v2-karg.stamp
        ExecStart=/bin/systemctl --no-block reboot

        [Install]
        WantedBy=multi-user.target
    - name: postgres.service
      enabled: true
      contents: |
        [Unit]
        Description=Run the database service for matrix
        After=network-online.target
        Wants=network-online.target

        [Service]
        ExecStart=/bin/podman run --name=postgres \
                                  --pull=always  \
                                  --read-only \
                                  --net=host \
                                  -e POSTGRES_USER=synapse \
                                  -e POSTGRES_DB=synapse \
                                  -e POSTGRES_INITDB_ARGS="--encoding='UTF8' --lc-collate='C' --lc-ctype='C'" \
                                  -e POSTGRES_PASSWORD=%%POSTGRES_PASSWORD%% \
                                  -v /var/srv:/var/lib/postgresql/data:z \
                                  docker.io/library/postgres:13
        ExecStop=/bin/podman rm -f postgres

        [Install]
        WantedBy=multi-user.target
